IOT-DSA/sdk-dslink-java

sdk/dslink/src/main/java/org/dsa/iot/dslink/provider/netty/DefaultWsProvider.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/provider/netty/WsClientCompressionHandler.java
This solves WebSocket Compression issues.
=> Fix WebSocket Compression

sdk/historian/src/main/java/org/dsa/iot/historian/database/Watch.java, sdk/historian/src/main/java/org/dsa/iot/historian/database/WatchGroup.java
Made the watch group take more decisions. Now the watch group keeps a list of watches so that it can poll values off its watches
=> T451 - interval cannot be changed while operational

sdk/dslink/src/main/java/org/dsa/iot/dslink/util/TimeUtils.java, sdk/dslink/src/test/java/org/dsa/iot/dslink/util/TimeUtilsTest.java
=> Aaron time utils

sdk/dslink/src/main/java/org/dsa/iot/dslink/connection/DataHandler.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/node/actions/table/Table.java
The user has confirmed these work.
=> Fix for streaming table modifications.

sdk/dslink/src/main/java/org/dsa/iot/dslink/util/TimeUtils.java, sdk/dslink/src/test/java/org/dsa/iot/dslink/util/TimeUtilsTest.java, sdk/historian/src/main/java/org/dsa/iot/historian/stats/GetHistory.java
@example6 See me about this.
-Aaron
=> Timezone fix

sdk/historian/src/main/java/org/dsa/iot/historian/database/OverwriteHistoryAction.java, sdk/historian/src/main/java/org/dsa/iot/historian/database/SubscriptionPool.java, sdk/historian/src/main/java/org/dsa/iot/historian/database/Watch.java, sdk/historian/src/main/java/org/dsa/iot/historian/database/WatchGroup.java, sdk/historian/src/main/java/org/dsa/iot/historian/utils/TimestampRange.java
=> Fix gethistory action alias

internal/logging/build.gradle, internal/runtime_shared/build.gradle
I need to install dslink to local maven repository but after looking at the gradle build files and found it is not supported for local. So I updated them.
=> updated build.gradle in internal/logging and internal/runtime_shared so they support to install to local maven repository

sdk/historian/src/main/java/org/dsa/iot/historian/stats/GetHistory.java, sdk/historian/src/main/java/org/dsa/iot/historian/stats/interval/IntervalParser.java, sdk/historian/src/main/java/org/dsa/iot/historian/stats/interval/IntervalProcessor.java
=> Fix time alignment and interval walking.

sdk/dslink/src/main/java/org/dsa/iot/dslink/connection/QueuedWriteManager.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/serializer/SerializationManager.java, sdk/historian/src/main/java/org/dsa/iot/historian/database/Watch.java
@kaendfinger This is a total blind guess.
=> Attempt to limit number of requests per message.

sdk/dslink/src/main/java/org/dsa/iot/dslink/node/value/ValueType.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/node/value/ValueUtils.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/serializer/Deserializer.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/serializer/SerializationManager.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/serializer/Serializer.java, sdk/historian/src/main/java/org/dsa/iot/historian/database/Watch.java
=> Password encryption & historian value conversion

internal/runtime_shared/src/main/java/org/dsa/iot/shared/SharedObjects.java
- Implement a new thread pool algorithm.
- Remove dangerous thread pool policies.
=> Improve Shared Thread Pool

sdk/dslink/src/main/java/org/dsa/iot/dslink/serializer/Serializer.java
@hhou2011 Can you test/review this?
=> Add original constructor back to Serializer.

sdk/dslink/src/main/java/org/dsa/iot/dslink/serializer/Deserializer.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/serializer/Serializer.java
=> Restore single arg constructor in Deserializer.

ci/script/run_integrated_tests.sh
@a-hansen @kaendfinger @hhou2011
=> Try the new Integrated tests script.

sdk/dslink/src/main/java/org/dsa/iot/dslink/DSLinkHandler.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/node/NodeManager.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/util/FileUtils.java
@Pacane @example6 - Icons coming in a pull request to the alarm link as an example.
=> Added icon support.

sdk/historian/src/main/java/org/dsa/iot/historian/database/WatchGroup.java
- Also added case where the watch isn't added when it's already present in a watch group.
=> Added result table for addWatchPath

sdk/dslink/src/main/java/org/dsa/iot/dslink/connection/DataHandler.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/link/Requester.java
@d-shapiro @Pacane Could either of you test and review?  Thanks.
=> Synchronous subscription updates.

build.gradle, sdk/dslink/src/main/java/org/dsa/iot/dslink/connection/ConnectionManager.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/connection/DataHandler.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/connection/QueuedWriteManager.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/node/SubscriptionManager.java
Apple memory leak and Cisco's out of order messages.
=> Aaron171102

build.gradle
sonatype complains about it for some reason
=> don't use + as junit version number

sdk/dslink/src/main/java/org/dsa/iot/dslink/methods/responses/ListResponse.java
=> fixed removal handling 

build.gradle, gradle/wrapper/gradle-wrapper.properties, sdk/dslink/src/main/java/org/dsa/iot/dslink/connection/QueuedWriteManager.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/node/MessageGenerator.java, sdk/dslink/src/main/java/org/dsa/iot/dslink/node/SubscriptionManager.java
Fix loss of subscription updates.
=> Aaron180806
